# Generated by Django 4.2 on 2024-05-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_invoice_product_cost_product_iva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, default='brands/default.png', null=True, upload_to='brands/'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='categories/default.png', null=True, upload_to='categories/'),
        ),
    ]
