# Generated by Django 4.2 on 2024-05-31 03:42

import django.core.validators
from django.db import migrations, models
import proy_sales.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_brand_image_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='default'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='default'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='default'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe contener entre 9 y 15 dígitos.', regex='^\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='ruc',
            field=models.CharField(max_length=10, validators=[proy_sales.utils.valida_cedula]),
        ),
    ]
